src/com/borischistov/mireapayments/controllers/AuthController.java
package com.borischistov.mireapayments.controllers;

import com.borischistov.mireapayments.entities.Person;
import com.borischistov.mireapayments.entities.utilis.AuthDetails;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

/**
 * Created with IntelliJ IDEA.
 * User: b_chistov
 * Date: 02.12.13
 * Time: 12:34
 */
@Component
@ManagedBean
@RequestScoped
public class AuthController {

    public Person getCurrentUser() {
        Person result = ((AuthDetails) SecurityContextHolder.getContext().getAuthentication().getPrincipal()).getPerson();
        return result;
    }
}

src/com/borischistov/mireapayments/controllers/EditContractController.java
package com.borischistov.mireapayments.controllers;

import com.borischistov.mireapayments.controllers.utils.NavUtils;
import com.borischistov.mireapayments.entities.Contract;
import com.borischistov.mireapayments.entities.Student;
import com.borischistov.mireapayments.services.api.IContractService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

/**
 * Created with IntelliJ IDEA.
 * User: b_chistov
 * Date: 11.11.13
 * Time: 10:15
 */
@Component
@ManagedBean
@RequestScoped
public class EditContractController {

    @Autowired
    private IContractService contractService;

    private Contract contract;
    private Student student;

    public void init() {
        if (contract == null && student == null) {
            NavUtils.setRedirect("BACK");
        } else if (contract == null) {
            contract = new Contract();
            contract.setStudent(student);
        }
    }

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Contract getContract() {
        return contract;
    }

    public void setContract(Contract contract) {
        this.contract = contract;
    }

    public void back() {
        contract = new Contract();
    }

    public String save() {
        try {
            contractService.save(contract);
            return NavUtils.SUCCESS;
        } catch (DataAccessException e) {
            e.printStackTrace();
        }
        return NavUtils.FAIL;
    }
}

src/com/borischistov/mireapayments/controllers/ManageContractController.java
package com.borischistov.mireapayments.controllers;

import com.borischistov.mireapayments.entities.Contract;
import com.borischistov.mireapayments.services.api.IContractService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: b_chistov
 * Date: 11.11.13
 * Time: 19:59
 */
@Component
@ManagedBean
@RequestScoped
public class ManageContractController {

    @Autowired
    private IContractService contractService;

    @Autowired
    private EditStudentController editStudentController;

    public List<Contract> getContractsByStudent() {
        if (editStudentController.getStudent() != null) {
            return contractService.getContracts(editStudentController.getStudent());
        } else {
            return null;
        }
    }

    public List<Contract> getContracts() {
        return contractService.getContracts();
    }
}

src/com/borischistov/mireapayments/controllers/ManageFormController.java
package com.borischistov.mireapayments.controllers;

import com.borischistov.mireapayments.entities.Form;
import com.borischistov.mireapayments.services.api.IFormService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: b_chistov
 * Date: 06.11.13
 * Time: 9:32
 */
@Component
@ManagedBean
@RequestScoped
public class ManageFormController {

    @Autowired
    private IFormService formService;

    private Form form;

    public ManageFormController() {
        this.form = new Form();
    }

    public void saveForm() {
        System.out.println(form.getName() + " " + form.getId());
        try {
            formService.saveForm(form);
        } catch (DuplicateKeyException e) {

        }
    }

    public void deleteForm(Form form) {
        formService.delete(form);
        this.form = new Form();
    }

    public void reset() {
        form = new Form();
    }

    public Form getForm() {
        return form;
    }

    public void selectForm(Form form) {
        this.form = form;
    }

    public List<Form> getForms() {
        return formService.getForms();
    }
}

src/com/borischistov/mireapayments/controllers/ManageGroupController.java
package com.borischistov.mireapayments.controllers;

import com.borischistov.mireapayments.entities.Group;
import com.borischistov.mireapayments.services.api.IGroupService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: Boris Chistov
 * Date: 07.11.13
 * Time: 22:26
 * Comment:
 */
@Component
@ManagedBean
@RequestScoped
public class ManageGroupController {

    @Autowired
    private IGroupService groupService;
    private Group group = new Group();

    public void reset() {
        group = new Group();
    }

    public void saveGroup() {
        groupService.save(group);
    }

    public void delete(Group group) {
        groupService.delete(group);
        reset();
    }

    public void selectGroup(Group group) {
        this.group = group;
    }

    public List<Group> getGroups() {
        return groupService.getGroups();
    }

    public Group getGroup() {
        return group;
    }

    public void setGroup(Group group) {
        this.group = group;
    }
}

src/com/borischistov/mireapayments/controllers/ManagePaymentController.java
package com.borischistov.mireapayments.controllers;

import com.borischistov.mireapayments.entities.Form;
import com.borischistov.mireapayments.entities.PaymentPlan;
import com.borischistov.mireapayments.entities.Speciality;
import com.borischistov.mireapayments.entities.StudySemester;
import com.borischistov.mireapayments.services.api.IFormService;
import com.borischistov.mireapayments.services.api.IPaymentPlanService;
import com.borischistov.mireapayments.services.api.ISemesterService;
import com.borischistov.mireapayments.services.api.ISpecialityService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import java.util.Date;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: b_chistov
 * Date: 25.11.13
 * Time: 10:49
 */
@Component
@ManagedBean
@RequestScoped
public class ManagePaymentController {

    private PaymentPlan paymentPlan;

    @Autowired
    private IPaymentPlanService paymentPlanService;
    @Autowired
    private ISemesterService semesterService;
    @Autowired
    private IFormService formService;
    @Autowired
    private ISpecialityService specialityService;

    public void init() {
        if (paymentPlan == null) {
            paymentPlan = new PaymentPlan();
            paymentPlan.setPaymentPlanCreationDate(new Date());
        }
    }

    public List<PaymentPlan> getPaymentPlans() {
        return paymentPlanService.getPlans();
    }

    public PaymentPlan getPaymentPlan() {
        return paymentPlan;
    }

    public void setPaymentPlan(PaymentPlan paymentPlan) {
        this.paymentPlan = paymentPlan;
    }

    public List<StudySemester> getStudySemesters() {
        return semesterService.getSemesters();
    }

    public List<Form> getForms() {
        return formService.getForms();
    }

    public List<Speciality> getSpecialities() {
        return specialityService.getSpecialities();
    }

    public void save() {
        try {
            paymentPlanService.save(paymentPlan);
            paymentPlan = new PaymentPlan();
        } catch (DataAccessException e) {

        }
    }

    public void reset() {
        paymentPlan = null;
    }

    public void select(PaymentPlan plan) {
        this.paymentPlan = plan;
    }
}

src/com/borischistov/mireapayments/controllers/ManageSpecialityController.java
package com.borischistov.mireapayments.controllers;

import com.borischistov.mireapayments.entities.Speciality;
import com.borischistov.mireapayments.services.api.ISpecialityService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: b_chistov
 * Date: 07.11.13
 * Time: 15:44
 */
@Component
@ManagedBean
@RequestScoped
public class ManageSpecialityController {

    @Autowired
    private ISpecialityService specialityService;
    private Speciality speciality = new Speciality();

    public List<Speciality> getSpecialities() {
        return specialityService.getSpecialities();
    }

    public void reset() {
        this.speciality = new Speciality();
    }

    public Speciality getSpeciality() {
        return speciality;
    }

    public void setSpeciality(Speciality speciality) {
        this.speciality = speciality;
    }

    public void saveSpeciality() {
        specialityService.saveSpeciality(speciality);
    }

    public void selectSpeciality(Speciality speciality) {
        this.speciality = speciality;
    }

    public void delete(Speciality speciality) {
        specialityService.delete(speciality);
        this.speciality = new Speciality();
    }
}

src/com/borischistov/mireapayments/controllers/ManageStatusController.java
package com.borischistov.mireapayments.controllers;

import com.borischistov.mireapayments.entities.Status;
import com.borischistov.mireapayments.services.api.IStatusService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: b_chistov
 * Date: 07.11.13
 * Time: 16:32
 */
@Component
@ManagedBean
@RequestScoped
public class ManageStatusController {

    @Autowired
    private IStatusService statusService;
    private Status status = new Status();

    public List<Status> getStatuses() {
        return statusService.getStatuses();
    }

    public void selectStatus(Status status) {
        this.status = status;
    }

    public void reset() {
        this.status = new Status();
    }

    public void save() {
        statusService.save(status);
    }

    public void delete(Status status) {
        statusService.delete(status);
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }
}

src/com/borischistov/mireapayments/controllers/ManageStudentInvoicesController.java
package com.borischistov.mireapayments.controllers;

import com.borischistov.mireapayments.entities.Contract;
import com.borischistov.mireapayments.entities.Invoice;
import com.borischistov.mireapayments.entities.StudySemester;
import com.borischistov.mireapayments.services.api.IContractService;
import com.borischistov.mireapayments.services.api.IInvoiceService;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.openxml4j.opc.OPCPackage;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: b_chistov
 * Date: 02.12.13
 * Time: 16:08
 */
@Component
@ManagedBean
@SessionScoped
public class ManageStudentInvoicesController {

    @Autowired
    private IContractService contractService;
    @Autowired
    private AuthController authController;
    @Autowired
    private IInvoiceService invoiceService;

    public List<Contract> getContractList() {
        List<Contract> result = contractService.getContracts(authController.getCurrentUser());
        return result;
    }

    public List<Invoice> getInvoices(Contract c) {
        List<Invoice> result = invoiceService.getInvoices(c);
        Collections.sort(result, new Comparator<Invoice>() {
            @Override
            public int compare(Invoice o1, Invoice o2) {
                StudySemester s1 = o1.getPlan().getStudySemester();
                StudySemester s2 = o2.getPlan().getStudySemester();
                if (s1.getStartYear() > s2.getStartYear()) {
                    return 1;
                } else if (s1.getStartYear() < s2.getStartYear()) {
                    return -1;
                } else {
                    if (s1.getSemester() > s2.getSemester()) {
                        return 1;
                    } else if (s1.getSemester() < s2.getSemester()) {
                        return -1;
                    } else {
                        return 0;
                    }
                }
            }
        });
        return result;
    }

    public void createInvoice(Invoice invoice) {
        invoice.setInvoiceCreationDate(new Date());
        invoice.setInvoiceNumber("NUMBER");
        invoiceService.save(invoice);
        downloadInvoice(invoice);
    }

    public void refreshInvoice(Invoice invoice) {
        downloadInvoice(invoice);
    }

    private void downloadInvoice(Invoice invoice) {
        try {
            ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
            ec.responseReset();
            ec.setResponseHeader("Content-Type", ec.getMimeType("invoices-template.docx"));
            ec.setResponseHeader("Content-Disposition", "attachment;filename=\"" + "invoice.docx" + "\"");
            XWPFDocument doc =
                    new XWPFDocument(OPCPackage.open(
                            ec.getResourceAsStream("/resources/templates/invoice-template.docx")));
            doc = invoiceService.prepareInvoiceFile(invoice, doc);
            OutputStream outputStream = ec.getResponseOutputStream();
            doc.write(outputStream);
            outputStream.close();
            FacesContext.getCurrentInstance().responseComplete();
        } catch (IOException e) {

        } catch (InvalidFormatException e) {

        }

    }
}

src/com/borischistov/mireapayments/controllers/ManageStudySemesterController.java
package com.borischistov.mireapayments.controllers;

import com.borischistov.mireapayments.entities.StudySemester;
import com.borischistov.mireapayments.services.api.ISemesterService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: Boris Chistov
 * Date: 11.11.13
 * Time: 0:02
 * Comment:
 */
@Component
@ManagedBean
@RequestScoped
public class ManageStudySemesterController {

    @Autowired
    private ISemesterService semesterService;

    private StudySemester semester = new StudySemester();

    public StudySemester getSemester() {
        return semester;
    }

    public List<StudySemester> getSemesters() {
        return semesterService.getSemesters();
    }

    public void setSemester(StudySemester semester) {
        this.semester = semester;
    }

    public void save() {
        semesterService.save(semester);
        semester = new StudySemester();
    }

    public void reset() {
        semester = new StudySemester();
    }

    public void selectSemester(StudySemester semester) {
        this.semester = semester;
    }

    public void delete(StudySemester semester) {
        semesterService.delete(semester);
    }
}

web/WEB-INF/templates/facelets/edit-contract.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Created by IntelliJ IDEA.
  User: b_chistov
  Date: 06.11.13
  Time: 9:37
-->
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">

<h:head>
    <title>Simple JSF Facelets page</title>
</h:head>

<h:body>
    <ui:composition template="content-template.xhtml">
        <ui:define name="panel-title">
            <h:outputLabel value="#{messages.EditContractTitle}"/>
        </ui:define>
        <ui:define name="panel-content">
            <h:form styleClass="form-horizontal">

                <!-- № Договора -->
                <div class="form-group">
                    <h:outputLabel value="#{messages.ContractNum}" styleClass="col-sm-4 control-label"/>

                    <div class="col-sm-6">
                        <h:inputText
                                id="contractNum" binding="#{contractNum}"
                                value="#{editContractController.contract.contractNumber}"
                                required="true" requiredMessage="#{messages.NotNullMsgSum}"
                                styleClass="form-control"/>
                    </div>

                </div>
                <div class="col-sm-10 alert alert-warning #{contractNum.valid ? 'hidden' : 'show'}">
                    <h:message for="contractNum"/>
                </div>

                <!-- Начало действия  -->
                <div class="form-group">
                    <h:outputLabel value="#{messages.ContractStart}" styleClass="col-sm-4 control-label"/>

                    <div class="col-sm-6">
                        <h:selectOneMenu value="#{editContractController.contract.startDate}"
                                         styleClass="form-control" id="contractStart" binding="#{contractStart}"
                                         required="true" requiredMessage="#{messages.NotNullMsgSum}">
                            <f:converter converterId="semesterConverter"/>
                            <f:selectItems value="#{manageStudySemesterController.semesters}" var="semester"
                                           itemLabel="#{semester.semester == 1 ? messages.StudySemester1 : messages.StudySemester2} - #{semester.startYear} / #{semester.endYear}"
                                           itemValue="#{semester}"/>
                        </h:selectOneMenu>
                    </div>

                </div>
                <div class="col-sm-10 alert alert-warning #{contractStart.valid ? 'hidden' : 'show'}">
                    <h:message for="contractStart"/>
                </div>

                <!-- Конец действия  -->
                <div class="form-group">
                    <h:outputLabel value="#{messages.ContractEnd}" styleClass="col-sm-4 control-label"/>

                    <div class="col-sm-6">
                        <h:selectOneMenu value="#{editContractController.contract.endDate}"
                                         styleClass="form-control" id="contractEnd" binding="#{contractEnd}"
                                         required="true" requiredMessage="#{messages.NotNullMsgSum}">
                            <f:converter converterId="semesterConverter"/>
                            <f:selectItems value="#{manageStudySemesterController.semesters}" var="semester"
                                           itemLabel="#{semester.semester == 1 ? messages.StudySemester1 : messages.StudySemester2} - #{semester.startYear} / #{semester.endYear}"
                                           itemValue="#{semester}"/>
                        </h:selectOneMenu>
                    </div>

                </div>
                <div class="col-sm-10 alert alert-warning #{contractEnd.valid ? 'hidden' : 'show'}">
                    <h:message for="contractEnd"/>
                </div>

                <!-- Студент  -->

                <div class="form-group">
                    <h:outputLabel value="#{messages.ContractFIO}" styleClass="col-sm-4 control-label"/>

                    <div class="col-sm-6">
                        <h:inputText
                                id="student" disabled="true"
                                value="#{editContractController.contract.student.lastName} #{editContractController.contract.student.firstName} #{editContractController.contract.student.surname}"
                                styleClass="form-control"/>
                    </div>
                </div>

                <!-- Форма обучения  -->
                <div class="form-group">
                    <h:outputLabel value="#{messages.ContractForm}" styleClass="col-sm-4 control-label"/>

                    <div class="col-sm-6">
                        <h:selectOneMenu value="#{editContractController.contract.form}"
                                         styleClass="form-control" id="contractForm" binding="#{contractForm}"
                                         required="true" requiredMessage="#{messages.NotNullMsgSum}">
                            <f:converter converterId="formConverter"/>
                            <f:selectItems value="#{manageFormController.forms}" var="form"
                                           itemLabel="#{form.name}"
                                           itemValue="#{form}"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="col-sm-10 alert alert-warning #{contractForm.valid ? 'hidden' : 'show'}">
                    <h:message for="contractForm"/>
                </div>

                <!-- Специальность  -->
                <div class="form-group">
                    <h:outputLabel value="#{messages.ContractSpeciality}" styleClass="col-sm-4 control-label"/>

                    <div class="col-sm-6">
                        <h:selectOneMenu value="#{editContractController.contract.speciality}"
                                         styleClass="form-control" id="contractSpeciality"
                                         binding="#{contractSpeciality}"
                                         required="true" requiredMessage="#{messages.NotNullMsgSum}">
                            <f:converter converterId="specialityConverter"/>
                            <f:selectItems value="#{manageSpecialityController.specialities}" var="speciality"
                                           itemLabel="#{speciality.specialityCode} - #{speciality.name}"
                                           itemValue="#{speciality}"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="col-sm-10 alert alert-warning #{contractSpeciality.valid ? 'hidden' : 'show'}">
                    <h:message for="contractSpeciality"/>
                </div>

                <!-- Группа  -->
                <div class="form-group">
                    <h:outputLabel value="#{messages.Group}" styleClass="col-sm-4 control-label"/>

                    <div class="col-sm-6">
                        <h:selectOneMenu value="#{editContractController.contract.group}"
                                         styleClass="form-control" id="contractGroup" binding="#{contractGroup}"
                                         required="true" requiredMessage="#{messages.NotNullMsgSum}"
                                >
                            <f:converter converterId="groupConverter"/>
                            <f:selectItems value="#{manageGroupController.groups}" var="group"
                                           itemLabel="#{group.name}"
                                           itemValue="#{group}"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="col-sm-10 alert alert-warning #{contractGroup.valid ? 'hidden' : 'show'}">
                    <h:message for="contractGroup"/>
                </div>

                <!-- Статус  -->
                <div class="form-group">
                    <h:outputLabel value="#{messages.Status}" styleClass="col-sm-4 control-label"/>

                    <div class="col-sm-6">
                        <h:selectOneMenu value="#{editContractController.contract.status}"
                                         styleClass="form-control" id="contractStatus" binding="#{contractStatus}"
                                         required="true" requiredMessage="#{messages.NotNullMsgSum}">
                            <f:converter converterId="statusConverter"/>
                            <f:selectItems value="#{manageStatusController.statuses}" var="status"
                                           itemLabel="#{status.name}"
                                           itemValue="#{status}"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="col-sm-10 alert alert-warning #{contractStatus.valid ? 'hidden' : 'show'}">
                    <h:message for="contractStatus"/>
                </div>

                <span class="help-block"><h:outputLabel value="* #{messages.StatusWarning}"/></span>

                <div class="col-sm-10 alert alert-warning #{(not facesContext.validationFailed) and (not empty facesContext.messageList) ? 'show' : 'hidden'}">
                    <h:messages showSummary="true" showDetail="true" globalOnly="true"/>
                </div>
                <div class="form-group">
                    <div class="btn-group col-sm-offset-1 col-sm-10">
                        <h:commandButton value="#{messages.SaveEdit}"
                                         action="#{editContractController.save}"
                                         styleClass="btn btn-primary">
                        </h:commandButton>
                        <h:commandButton value="#{messages.GoBack}"
                                         immediate="true"
                                         actionListener="#{editContractController.back}"
                                         styleClass="btn btn-default"
                                         onclick="history.back(); return false;">
                        </h:commandButton>
                    </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>

</html>

web/WEB-INF/templates/facelets/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Created by IntelliJ IDEA.
  User: b_chistov
  Date: 05.11.13
  Time: 14:57
-->
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
        >

<h:head>
    <h:outputStylesheet library="css" name="bootstrap.min.css"/>
    <title>Simple JSF Facelets page</title>
</h:head>

<h:body>
    <ui:composition>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Учебный процес<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <ui:repeat value="#{menuController.studyMenus}" var="menu">
                            <li class="#{menu.viewID eq facesContext.viewRoot.viewId ? 'active' : ''}"><h:link
                                    value="#{messages[menu.menuName]}"
                                    outcome="#{menu.viewID}"/></li>

                        </ui:repeat>
                    </ul>

                </li>

            </ul>
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Финансы<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <ui:repeat value="#{menuController.financeMenus}" var="menu">
                            <li class="#{menu.viewID eq facesContext.viewRoot.viewId ? 'active' : ''}"><h:link
                                    value="#{messages[menu.menuName]}"
                                    outcome="#{menu.viewID}"/></li>

                        </ui:repeat>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><h:outputLink value="#">
                    <h:outputLabel value="#{authController.currentUser.lastName}
                    #{authController.currentUser.firstName.charAt(0)}.
                    #{authController.currentUser.surname.charAt(0)}."/>
                </h:outputLink></li>
                <li><a href="#{request.contextPath}/j_spring_security_logout">Выйти</a></li>
            </ul>
        </div>
    </ui:composition>
    <h:outputScript library="js" name="jquery.js"/>
    <h:outputScript library="js" name="bootstrap.min.js"/>
</h:body>

</html>